export default {
    _id: '5e544facbd427b6e9cd9059e',
    id: 900000011,
    lastname: 'Nei',
    bio: 'Jefferson Comprehensive Epilepsy Center',
    firstname: 'Maromi',
    type: 'person',
    tags: ['Neuroendocrinology', 'Epilepsy', 'Neuroscience'],
    activeflag: 'active',
    authors: [''],
    counter: 73,
    relatedresources: 0,
    persons: [],
    updated: 1621551600000,
};
