//*** local variables used in exports

var site      = 'web.dev.hdruk.cloud';
var email     = process.env.GATEWAY_USER;
var password  = process.env.GATEWAY_PASSWORD;

var ignoreDefault = [
  "WCAG2AAA.Principle1.Guideline1_4.1_4_3_F24.F24.FGColour",            // check for inherited BG color to complement inline FG color
  "WCAG2AAA.Principle1.Guideline1_4.1_4_6.G17.Fail",                    // insufficient contrast: 7:1
  "WCAG2AAA.Principle1.Guideline1_4.1_4_6.G18.Fail",                    // insufficient contrast: 4.5:1
  // mostly for menus with cdk-overlay-container, cdk-global-overlay
  "WCAG2AAA.Principle1.Guideline1_4.1_4_10.C32,C31,C33,C38,SCR34,G206", // element has 'position: fixed'
];

var ignoreNotForm = [ ... ignoreDefault,
  "WCAG2AAA.Principle1.Guideline1_3.1_3_1.H44.NotFormControl"           // 'for' should point to form control (mat-select without control)
];

/**
 * Configuration for Pa11y-ci.
 */
module.exports = {

  // NOTE: defaults are OVERRIDDEN not extended
  defaults : {
    chromeLaunchConfig          : { 
        executablePath              : "/usr/bin/google-chrome-stable",
        args                        : ['--no-sandbox']
     },
    // concurrency=1 so urls are sequential, with login first (if browser context is preserved)
    concurrency                 : 1,
    ignore                      : ignoreDefault,
    // true to include non-actionable notices  (false by default)
    includeNotices              : true,
    // true to include non-actionable warnings (false by default)
    includeWarnings             : true,
    // e.g., error, warning, or notice
    level                       : "error",
    runners                     : ["axe"],
    // e.g., WCAG2A, WCAG2AA, WCAG2AAA (low to high), Section508 (deprecated)
    standard                    : "WCAG2A",
    // timeout (in msec) for an entire test run
    timeout                     : 10000,
    // false to preserve browser context
    useIncognitoBrowserContext  : false,
  },

  urls : [
    { url     : `${site}/sign-in`,
    actions : [
      "wait for url to be https://web.dev.hdruk.cloud/en/sign-in",
      `set field input[name=email] to ${email}`,
      `set field input[name=password] to ${password}`,
      `click element button[type=submit]`,
      "wait for url to be https://web.dev.hdruk.cloud/en/account/profile",
    ],
  },
    { ignore  : ignoreNotForm,
      url     : `${site}`,
      timeout : 50000,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/dataset/1`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/about/cohort-discovery`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/about/cohort-discovery-request`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/about/contact-us`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/about/data-custodians`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/about/development-community`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/about/meet-the-team`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/about/our-mission-and-purpose`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/about/patients-and-public`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/about/researchers-innovators,`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/collection/1`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/community/work-with-us`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/data-custodian/1`,
      timeout : 50000,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/data-custodian/getting-started`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/data-use/1`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/help/glossary`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/help/tutorials`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/how-to-search`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/news/releases`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/newsletter-signup`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/search`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/search?sampleAvailability`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/search?type=dur`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/search?type=collections`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/search?type=data_providers`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/search?type=tools`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/support/cohort-discovery`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/support/data-access-request`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/support/data-use-register`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/support/gateway-schema`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/support`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/support/team-management`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/support/tools`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/terms-and-conditions`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/profile/cohort-discovery-admin/1`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/profile/cohort-discovery-admin`,
    },
    //These are not working at the moment due to functionality missing or no data
    // { ignore  : ignoreNotForm,
    //   url     : ` /tool/1`,
    // },
    // { ignore  : ignoreNotForm,
    //   url     : `${site} /account/data-access-requests/application/1`,
    // },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/profile/dar-admin/question-bank/1`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/profile/dar-admin/question-bank/create`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/profile/dar-admin/question-bank/list`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/profile/dar-admin/question-bank`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/profile/library`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/profile`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/profile/publications`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/profile/saved-searches`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/profile/teams/1`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/profile/teams/create`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/profile/teams`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/profile/tools`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/data-access-requests/applications`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/data-access-requests/edit-form`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/data-access-requests/templates`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/data-access-requests/workflows`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/data-uses/1`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/data-uses/create`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/data-uses`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/datasets`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/datasets/upload`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/help`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/integrations/api-management/create/1`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/integrations/api-management/create/1/permissions`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/integrations/api-management/create`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/integrations/api-management/list`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/integrations/api-management/list/1`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/integrations/api-management`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/integrations/integration/create`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/integrations/integration/list/1`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/integrations/integration/list`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/integrations/api-management`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/integrations/integration/create`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/integrations/integration/list/1`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/integrations/integration/list`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/integrations/integration`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/team-management`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/tools/1`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/tools/create`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/tools`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/data-access-requests/templates/1/edit`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/datasets/72`,
    },
    { ignore  : ignoreNotForm,
      url     : `${site}/account/team/1/datasets/create`,
    },
  ],

}; // end module.exports
