const CUSTOMER_PORTAL_SUPPORT_URL =
    process.env.NEXT_PUBLIC_CUSTOMER_PORTAL_SUPPORT_URL;
const GATEWAY_TERMS_URL = process.env.NEXT_PUBLIC_GATEWAY_TERMS_URL;
const CUSTOMER_PORTAL_RAISE_SUPPORT_URL =
    process.env.NEXT_PUBLIC_CUSTOMER_PORTAL_RAISE_SUPPORT_URL;

export {
    CUSTOMER_PORTAL_SUPPORT_URL,
    GATEWAY_TERMS_URL,
    CUSTOMER_PORTAL_RAISE_SUPPORT_URL,
};
