const CUSTOMER_PORTAL_SUPPORT_URL =
    process.env.NEXT_PUBLIC_CUSTOMER_PORTAL_SUPPORT_URL;
const GATEWAY_TERMS_URL = process.env.NEXT_PUBLIC_GATEWAY_TERMS_URL;

export { CUSTOMER_PORTAL_SUPPORT_URL, GATEWAY_TERMS_URL };
