const ROLE_CUSTODIAN_TEAM_ADMIN = 'custodian.team.admin';
const ROLE_CUSTODIAN_DAR_MANAGER = 'custodian.dar.manager';
const ROLE_CUSTODIAN_METADATA_MANAGER = 'custodian.metadata.manager';

export { ROLE_CUSTODIAN_TEAM_ADMIN, ROLE_CUSTODIAN_DAR_MANAGER, ROLE_CUSTODIAN_METADATA_MANAGER };
