const ROLE_CUSTODIAN_DEVELOPER = "developer";
const ROLE_CUSTODIAN_TEAM_ADMIN = "custodian.team.admin";
const ROLE_CUSTODIAN_METADATA_MANAGER = "custodian.metadata.manager";
const ROLE_CUSTODIAN_METADATA_EDITOR = "metadata_editor";
const ROLE_CUSTODIAN_DAR_MANAGER = "custodian.dar.manager";
const ROLE_CUSTODIAN_DAR_REVIEWER = "reviewer";

const ROLE_HDRUK_ADMIN = "hdruk.admin";
const ROLE_HDRUK_SUPERADMIN = "hdruk.superadmin";
const ROLE_HDRUK_METADATA = "hdruk.metadata";
const ROLE_HDRUK_DAR = "hdruk.dar";
const ROLE_HDRUK_CUSTODIAN = "hdruk.custodian";

export {
    ROLE_CUSTODIAN_DEVELOPER,
    ROLE_CUSTODIAN_TEAM_ADMIN,
    ROLE_CUSTODIAN_METADATA_MANAGER,
    ROLE_CUSTODIAN_METADATA_EDITOR,
    ROLE_CUSTODIAN_DAR_MANAGER,
    ROLE_CUSTODIAN_DAR_REVIEWER,
    ROLE_HDRUK_ADMIN,
    ROLE_HDRUK_SUPERADMIN,
    ROLE_HDRUK_METADATA,
    ROLE_HDRUK_DAR,
    ROLE_HDRUK_CUSTODIAN,
};
