const ROLE_CUSTODIAN_TEAM_ADMIN = 'custodian.team.admin';
const ROLE_CUSTODIAN_DAR_MANAGER = 'custodian.dar.manager';
const ROLE_CUSTODIAN_DAR_REVIEWER = 'reviewer';
const ROLE_CUSTODIAN_METADATA_MANAGER = 'custodian.metadata.manager';
const ROLE_CUSTODIAN_METADATA_EDITOR = 'metadata_editor';

export {
    ROLE_CUSTODIAN_TEAM_ADMIN,
    ROLE_CUSTODIAN_DAR_MANAGER,
    ROLE_CUSTODIAN_METADATA_MANAGER,
    ROLE_CUSTODIAN_DAR_REVIEWER,
    ROLE_CUSTODIAN_METADATA_EDITOR,
};
