export enum RouteName {
    ABOUT = "about",
    ACCOUNT = "account",
    APPLICATIONS = "applications",
    API_MANAGEMENT = "api-management",
    COHORT_DISCOVERY = "cohort-discovery",
    COHORT_DISCOVERY_ADMIN = "cohort-discovery-admin",
    CREATE = "create",
    DATA_ACCESS_REQUESTS = "data-access-requests",
    DATA_USES = "data-uses",
    DATASETS = "datasets",
    DUPLICATE = "duplicate",
    EDIT_FORM = "edit-form",
    EN = "en",
    HELP = "help",
    INTEGRATION = "integration",
    INTEGRATIONS = "integrations",
    LIST = "list",
    PERMISSIONS = "permissions",
    PROFILE = "profile",
    TEAM = "team",
    TEAM_MANAGEMENT = "team-management",
    WORKFLOWS = "workflows",
    TERMS = "terms-and-conditions",
}
