import {
    ROLE_CUSTODIAN_DAR_MANAGER,
    ROLE_CUSTODIAN_DAR_REVIEWER,
    ROLE_CUSTODIAN_DEVELOPER,
    ROLE_CUSTODIAN_METADATA_EDITOR,
    ROLE_CUSTODIAN_METADATA_MANAGER,
    ROLE_CUSTODIAN_TEAM_ADMIN,
} from "@/consts/roles";

const permissions = {
    [ROLE_CUSTODIAN_DEVELOPER]: [],
    [ROLE_CUSTODIAN_TEAM_ADMIN]: [],
    [ROLE_CUSTODIAN_DAR_MANAGER]: [
        ROLE_CUSTODIAN_DAR_MANAGER,
        ROLE_CUSTODIAN_DAR_REVIEWER,
    ],
    [ROLE_CUSTODIAN_DAR_REVIEWER]: [],
    [ROLE_CUSTODIAN_METADATA_MANAGER]: [
        ROLE_CUSTODIAN_METADATA_MANAGER,
        ROLE_CUSTODIAN_METADATA_EDITOR,
    ],
    [ROLE_CUSTODIAN_METADATA_EDITOR]: [],
};

export { permissions as TeamManagementPermissions };
