name: Lint GitHub Workflows

permissions:
  contents: read
  actions: read

on:
  pull_request:
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"

  push:
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"

jobs:
  actionlint:
    uses: HDRUK/github-actions-templates/.github/workflows/actionlint.yaml@main