name: Run quality checks
run-name: ${{ github.actor }} triggered quality check pipeline
on:
  push:
    branches:
      - dev
      - main
      - 'GAT-2588'
  pull_request:
    branches:
      - main
      - dev
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: NPM install
      run: "npm install"
     
    # - name: Run lint #Disabled because it's failing currently
    #   run: "npm run lint"

    - name: Run unit tests
      run: "npm run test"