name: Run quality checks
run-name: ${{ github.actor }} triggered quality check pipeline
on:
  push:
    branches:
      - dev
      - staging
      - main
  pull_request:
    branches:
      - main
      - staging
      - dev
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: NPM install
        run: "npm install"

      - name: Run lint
        run: "npm run lint"

      - name: Run unit tests
        run: "npm run test"
