name: Deploy Release
run-name: ${{ github.actor }} triggered deploy to ${{ github.event.inputs.env }} pipeline for tag version ${{ github.event.inputs.tag_version }}

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Select environment to deploy'
        required: true
        default: 'preprod'
        type: choice
        options:
          - preprod
          - prod
      tag_version:
        description: 'Tag version to deploy'
        required: true
        default: ''

jobs:
  deploy:
    uses: HDRUK/github-actions-templates/.github/workflows/deploy-release.yml@main
    with:
      env: ${{ github.event.inputs.env }}
      tag_version: ${{ github.event.inputs.tag_version }}
      chart_path: chart/gateway-web/Chart.yaml
      git_ref: main
    secrets: inherit