name: Build and deploy to DEV
run-name:  ${{ github.actor }} triggered deploy to DEV pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    with:
      chart_path: chart/gateway-web/Chart.yaml
      gar_name: gateway-web
      environments: '["dev"]'
    secrets: inherit

  deploy:
    needs: build
    uses: HDRUK/github-actions-templates/.github/workflows/deploy-release.yml@main
    with:
      env: dev
      chart_path: chart/gateway-web/Chart.yaml
      git_ref: dev
    secrets: inherit