name: Build and deploy to DEV
run-name:  ${{ github.actor }} triggered deploy to DEV pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    with:
      chart_path: chart/gateway-web/Chart.yaml
      gar_name: gateway-web
      environments: '["dev"]'
      docker_build_args: >
        --build-arg NEXT_PUBLIC_API_V1_URL=${{ vars.NEXT_PUBLIC_API_V1_URL }} 
        --build-arg NEXT_PUBLIC_API_V1_IP_URL=${{ vars.NEXT_PUBLIC_API_V1_IP_URL }} 
        --build-arg NEXT_PUBLIC_API_V2_URL=${{ vars.NEXT_PUBLIC_API_V2_URL }} 
        --build-arg NEXT_PUBLIC_API_V2_IP_URL=${{ vars.NEXT_PUBLIC_API_V2_IP_URL }} 
        --build-arg NEXT_PUBLIC_API_VERSION=${{ vars.NEXT_PUBLIC_API_VERSION}} 
        --build-arg NEXT_PUBLIC_API_BASE_URL=${{ vars.NEXT_PUBLIC_API_BASE_URL }} 
        --build-arg NEXT_PUBLIC_WORDPRESS_API_URL=${{ vars.NEXT_PUBLIC_WORDPRESS_API_URL }} 
        --build-arg NEXT_PUBLIC_SERVICE_DESK_URL=${{ vars.NEXT_PUBLIC_SERVICE_DESK_URL }} 
        --build-arg NEXT_PUBLIC_GATEWAY_URL=${{ vars.NEXT_PUBLIC_GATEWAY_URL }} 
        --build-arg NEXT_PUBLIC_HOTJAR_ID=${{ vars.NEXT_PUBLIC_HOTJAR_ID }} 
        --build-arg NEXT_PUBLIC_SCHEMA_NAME=${{ vars.NEXT_PUBLIC_SCHEMA_NAME }} 
        --build-arg TRASER_SERVICE_URL=${{ vars.TRASER_SERVICE_URL }} 
        --build-arg NEXT_PUBLIC_SCHEMA_VERSION=${{ vars.NEXT_PUBLIC_SCHEMA_VERSION }} 
        --build-arg NEXT_PUBLIC_SCHEMA_BRANCH=${{ vars.NEXT_PUBLIC_SCHEMA_BRANCH }} 
        --build-arg NEXT_PUBLIC_GTM_ID=${{ vars.NEXT_PUBLIC_GTM_ID }} 
        --build-arg NEXT_PUBLIC_OA_APP_ID=${{ vars.NEXT_PUBLIC_OA_APP_ID }} 
        --build-arg NEXT_PUBLIC_MEDIA_DOMAIN=${{ vars.NEXT_PUBLIC_MEDIA_DOMAIN }} 
        --build-arg NEXT_PUBLIC_MEDIA_STATIC_URL=${{ vars.NEXT_PUBLIC_MEDIA_STATIC_URL }} 
        --build-arg NEXT_PUBLIC_PREDEFINED_INTEGRATION_OVERVIEW_URL=${{ vars.NEXT_PUBLIC_PREDEFINED_INTEGRATION_OVERVIEW_URL }} 
        --build-arg NEXT_PUBLIC_CONFLUENCE_URL=${{ vars.NEXT_PUBLIC_CONFLUENCE_URL }} 
        --build-arg NEXT_PUBLIC_CUSTOM_INTEGRATION_OVERVIEW_URL=${{ vars.NEXT_PUBLIC_CUSTOM_INTEGRATION_OVERVIEW_URL }}
    secrets: inherit

  deploy:
    needs: build
    uses: HDRUK/github-actions-templates/.github/workflows/deploy-release.yml@main
    with:
      env: dev
      chart_path: chart/gateway-web/Chart.yaml
      git_ref: dev
    secrets: inherit