name: PR Title Validation

permissions:
  contents: read
  actions: read

on:
  pull_request:
    types: [opened, edited, synchronize]


jobs:
  check-title:
    uses: HDRUK/github-actions-templates/.github/workflows/pr-title-check.yml@main
    secrets: inherit