name: Deploy to Cloud Run

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'

env:
  PROJECT_ID: '${{ secrets.PROJECT_ID }}' # TODO: update Google Cloud project id.
  GAR_LOCATION: '${{ secrets.GAR_LOCATION }}' # TODO: update Artifact Registry location

jobs:      # Deployment please don't modify anything here as the infrastructure is controlled by terraform any changes here please agree with chris and reuben

  deploy:
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest
    environment: legacy-prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' 
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Read VERSION file
        id: getversion
        run: echo "version=$(cat Chart.yaml)" >> $GITHUB_OUTPUT
      
      - name: Create the release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: 'GAT Live Release - ''${{ steps.getversion.outputs.version }}'
          prerelease: false        

      - name: Deploy to Cloud Run
        uses: actions-hub/gcloud@master
        id: deploy
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          DEV_PROJECT_ID: ${{ secrets.DEV_PROJECT_ID }}
          GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
          GAR_NAME: ${{ secrets.GAR_NAME_WEB }}
          SERVICE_NAME: '${{ secrets.SERVICE_NAME_WEB }}'
          SERVICE_REGION: '${{ secrets.SERVICE_REGION_WEB }}'

        with:
          # args: run services update '${{ env.SERVICE_NAME }}' --image='${{ env.GAR_LOCATION }}'-docker.pkg.dev/'${{ env.DEV_PROJECT_ID }}'/'${{ env.GAR_NAME }}'/${{ steps.getversion.outputs.version }}:${{ github.sha }} --region='${{ env.SERVICE_REGION }}' --project='${{ env.PROJECT_ID }}' 
          args: run services update '${{ env.SERVICE_NAME }}' --image='${{ env.GAR_LOCATION }}'-docker.pkg.dev/'${{ env.DEV_PROJECT_ID }}'/'${{ env.GAR_NAME }}'/${{ steps.getversion.outputs.version }}:latest --region='${{ env.SERVICE_REGION }}' --project='${{ env.PROJECT_ID }}'
      # If required, use the Cloud Run url output in later steps
      
      - name: Deploy Notification
        id: deploynotificationsent
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: ${{ env.SLACK_CHANNEL }}
          message: Deploying {{ env.GITHUB_REF_NAME }} branch
        if: always()
