name: Semantic Release workflow

permissions:
  contents: write
  pull-requests: write
  issues: write
  checks: write
  statuses: write
  actions: write
  packages: write
  pages: write
  id-token: write
  deployments: write
  repository-projects: write
  security-events: write
  artifact-metadata: write
  attestations: write
  discussions: write
  models: read

on:
  push:
    branches:
      - main

jobs:
  semantic:
    uses: HDRUK/github-actions-templates/.github/workflows/semantic.yaml@main
    with:
      chart_path: chart/gateway-web/Chart.yaml
    secrets: inherit