name: Semantic Release workflow

on:
  push:
    branches:
      - main

jobs:
  semantic:
    uses: HDRUK/github-actions-templates/.github/workflows/semantic.yaml@main
    with:
      chart_path: chart/gateway-web/Chart.yaml
    secrets: inherit

  setup-preprod:
    uses: ./.github/workflows/build-args.yaml
    with:
     environment: preprod

  setup-prod:
    uses: ./.github/workflows/build-args.yaml
    with:
     environment: prod

  build-preprod:
    needs: setup-preprod
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    with:
      environment: preprod
      docker_build_args: ${{ needs.setup-preprod.outputs.docker_build_args }}
      chart_path: chart/gateway-web/Chart.yaml
    secrets: inherit

  build-prod:
    needs: setup-prod
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    with:
      environment: prod
      docker_build_args: ${{ needs.setup-prod.outputs.docker_build_args }}
      chart_path: chart/gateway-web/Chart.yaml
    secrets: inherit
