name: Semantic Release workflow

on:
  push:
    branches:
      - main

jobs:
  semantic:
    uses: HDRUK/github-actions-templates/.github/workflows/semantic.yaml@main
    with:
      chart_path: chart/gateway-web/Chart.yaml
    secrets: inherit